update config for compatibility with 4.x gcp provider
FairwindsOps/terraform-gke pull request #47
Opened 2021-12-15 16:33 UTC by dosullivan

Couple minor tweaks necessary for compatibility with the newer 4.x gcp provider version. `username` and `password` were removed entirely from the `master_auth` config block of `google_container_cluster`; otherwise a couple workload identity bits changed for the node pool config. Note that `GKE_METADATA_SERVER` has to be input as `GKE_METADATA` now. 

I tested updating the `vpc-native` and `node_pool` modules on an existing cluster and it seemed to work fine -- terraform reported no changes were necessary.

2021-12-20 16:21 UTC, lucasreed requested changes
👋  Hey @dosullivan, could we actually make the required provider version of this PR `3.90.0` and then have a separate PR and module version increase  for the provider bump to `4.0.0`? This would allow an upgrade path to the new variables that's available in the `3.X` version space before upgrading the provider.

I did some looking and it looks like all the deprecations/new variables are available in provider version `3.90.0`.

Also could you update the CHANGELOG? You can reference the next minor release in each updated module. When we update to `4.0.0` we'll major release.

2021-12-20 16:24 UTC, lucasreed commented
@dosullivan When you update the README/CHANGELOG, can you also include the new variable added with [this PR](https://github.com/FairwindsOps/terraform-gke/pull/46) and we'll release this module with a new minor version including that change and these changes.

2021-12-21 17:14 UTC, dosullivan commented
Sure thing! Just updated the provider versions and the changelog for each module, including a note about the new `image_type` parameter. I think it should be ready to go now, but let me know if you need anything else.

2021-12-22 19:02 UTC, lucasreed approved these changes

2021-12-22 19:03 UTC, merged